version: "3"

services:

# app:
#     build:
#       context: .
#       dockerfile: VehicleTax/Dockerfile
#     restart: always
#     ports:
#       - "3000:3000"
#     depends_on:
#       - pg
  pg:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_DB: gra
      POSTGRES_USER: gra
      POSTGRES_PASSWORD: 1
    ports:
      - "5409:5432"